### ISSUE TITLE
Change of domain and / or duration configuration

### ISSUE THREAD

**Issue by Artman109** [CW3E/Operations-Planning#4]
** What product do you need a different configuration for? 

> GFS Deterministic - 12Z
> ECMWF Deterministic - 12Z

** Why are you requesting this change? 

It would be good to implement Wrf-Chem.    It appears the current microphysics configuration does not remove enough of the condensate over the shallower coastal mtns or may simply not produce enough condensate given the shallow nature of the terrain and produces too much condensate and is too efficient in removing that condensate over the higher elevations.  Aerosols are known to impact the collision-coalescence process in maritime clouds and Wrf-Chem would allow testing the sensitivity of precipitation to these effects.   

** Is this to meet the requirement of a grant or contract held by CW3E or partners? If so, which one? 

Yes.  If the cloud seeding proposal is funded we will need a 1 km hourly output Wrf-Chem running to support cloud-seeding  operators.  

** What change would you like to see implemented? see above

** Why should this be implemented?  Improve precipitation forecasts within the deterministic runs of West-Wrf and provide seeding methods and targeting decision support to operators.  

** What is the importance of this?**
> Must have if proposal funded

** When do you need this ready by? **

> 2024 or 2025 Wet season

**Comment by Artman109** [comment]
Really only need 24 hr forecast but we be nice to hot start the run so we do not have to spin-up the precip and cloud moisture.  Run a specific 1 km domain covering the operators we are feeding data to using other resources or nodes just for these runs and pull from the NRT 9 and 3 km runs.  A smaller domain a with 1 h output with the cloud 3-D variables.  Using WRF-Chem provide forward trajectories for various surface based release sites backward trajectories for an aerial seeding line that would have fallout over the designated watershed.

**Comment by dfsteinhoff** [comment]
Implementing WRF-Chem into the operational framework is not feasible right now due to 1) limited additional computational resources available in light of the considerable increase in computational cost associated with WRF-Chem and trajectories; 2) the extensive setup and testing needed to run WRF-Chem operationally.  The computational resources and effort needed for these tasks should be requested through the project funding unless CW3E management has specifically decided to otherwise absorb those costs.  As for the hot start, we are planning to address this issue through either DFI or FDDA for the coming season.
